# Generated by Django 4.2.4 on 2023-10-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='Age',
            new_name='Mobile',
        ),
        migrations.AddField(
            model_name='userdb',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
