# Generated by Django 4.2.4 on 2023-10-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_rename_age_userdb_mobile_userdb_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Cat_Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('Cat_Image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
