# Generated by Django 4.2.4 on 2023-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_catdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProCat_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('ProName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProPrice', models.IntegerField(blank=True, null=True)),
                ('Pro_Desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
