# Generated by Django 4.2.4 on 2023-10-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Pswd', models.CharField(blank=True, max_length=50, null=True)),
                ('CfrmPswd', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
