# Generated by Django 4.2.4 on 2023-10-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaceapp', '0003_servicedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedb',
            name='Request',
        ),
        migrations.AddField(
            model_name='servicedb',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
